language: csharp
solution: MajorsilenceReporting-Linux.sln
install:
  - sudo apt-get install mono-devel nunit-console libpoppler-cil xvfb libgtk2.0-cil libpoppler-cil nuget 
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo apt-get install ttf-mscorefonts-installer -y > /dev/null
 
script:
  - nuget restore ./MajorsilenceReporting-Linux.sln -NonInteractive
  - xbuild /p:Configuration=Release MajorsilenceReporting-Linux.sln
  - nunit-console ./ReportTests/bin/Release/ReportTests.dll -exclude Integration,NotWorkingOnMono
